/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demopkg_Process */

#ifndef _Included_demopkg_Process
#define _Included_demopkg_Process
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demopkg_Process
 * Method:    nativeLongOperation
 * Signature: (Ldemopkg/ICallback;)V
 */
JNIEXPORT void JNICALL Java_demopkg_Process_nativeLongOperation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
