/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demopkg_Wrapper */

#ifndef _Included_demopkg_Wrapper
#define _Included_demopkg_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demopkg_Wrapper
 * Method:    nativeInitDll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_demopkg_Wrapper_nativeInitDll
  (JNIEnv *, jobject);

/*
 * Class:     demopkg_Wrapper
 * Method:    nativeExtract
 * Signature: (Ldemopkg/ICallback;)V
 */
JNIEXPORT void JNICALL Java_demopkg_Wrapper_nativeExtract
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
