/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Process */

#ifndef _Included_Process
#define _Included_Process
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Process
 * Method:    nativeLongOperation
 * Signature: (LICallback;)V
 */
JNIEXPORT void JNICALL Java_Process_nativeLongOperation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
